# Generated by Django 3.1.1 on 2020-10-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='today',
            field=models.DateTimeField(),
        ),
    ]
