# Generated by Django 3.1.1 on 2020-10-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201021_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='today',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
